# Load the data.frame package
library(data.frame)

# Create the R dataframe
crash_data_descriptions <- data.frame(
  Attribute_Name = c(
    'advisorySpeed', 'areaUnitID', 'bicycle', 'bridge', 'bus',
    'carStationWagon', 'cliffBank', 'crashDirectionDescription',
    'crashDistance', 'crashFinancialYear', 'crashLocation1', 'crashLocation2',
    'crashSeverity', 'crashSHDescription1', 'crashYear', 'debris',
    'directionRoleDescription', 'ditch', 'easting', 'fatalCount',
    'fence', 'flatHill', 'guardRail', 'holiday', 'houseOrBuilding',
    'intersectionMidblock', 'kerb', 'light', 'meshblockId', 'minorInjuryCount',
    'moped', 'motorcycle', 'northing', 'NumberOfLanes', 'objectThrownOrDropped',
    'otherObject', 'otherVehicleType', 'overBank', 'parkedVehicle', 'phoneBoxEtc',
    'pedestrian', 'postOrPole', 'region', 'roadCharacter1', 'roadLane',
    'roadMarkings', 'roadSurface', 'roadworks', 'schoolBus', 'seriousInjuryCount',
    'slipOrFlood', 'speedLimit', 'strayAnimal', 'streetLight', 'suv',
    'taxi', 'tlaId', 'tlaName', 'temporarySpeedLimit', 'trafficControl',
    'trafficIsland', 'trafficSign', 'train', 'tree', 'truck',
    'unknownVehicleType', 'urban', 'vanOrUtility', 'vehicle', 'waterRiver',
    'weatherA', 'weatherB'
  ),
  Alias_Name = c(
    'Advisory Speed', 'Area Unit ID', 'Bicycle', 'Bridge', 'Bus',
    'Car/Station Wagon', 'Cliff or Bank', 'Crash Direction Description',
    'Crash Distance', 'Crash Financial Year', 'Crash Location 1', 'Crash Location 2',
    'Crash Severity', 'Crash SH Description', 'Crash Year', 'Debris',
    'Direction Role Description', 'Ditch', 'Easting', 'Fatal Count',
    'Fence', 'Flat Hill', 'Guard Rail', 'Holiday', 'House or Building',
    'Intersection Midblock', 'Kerb', 'Light', 'Meshblock ID', 'Minor Injury Count',
    'Moped', 'Motorcycle', 'Northing', 'Number of Lanes', 'Object thrown or dropped',
    'Other Object', 'Other Vehicle Type', 'Over Bank', 'Parked Vehicle', 'Phone Box etc.',
    'Pedestrian', 'Post or Pole', 'Region', 'Road Character', 'Road Lane',
    'Road Markings', 'Road Surface', 'Road works', 'School Bus', 'Serious Injury Count',
    'Slip or Flood', 'Speed Limit', 'Stray Animal', 'Street Light', 'SUV',
    'Taxi', 'TLA ID', 'TLA Name', 'Temporary Speed Limit', 'Traffic Control',
    'Traffic Island', 'Traffic Sign', 'Train', 'Tree', 'Truck',
    'Unknown Vehicle Type', 'Urban', 'Van or Utility', 'Vehicle', 'Water River',
    'Weather A', 'Weather B'
  ),
  Description = c(
    'The advisory (adv) speed (spd) at the crash site at the time of the crash.',
    'The unique identifier of an area unit.',
    'Derived variable to indicate how many bicycles were involved in the crash.',
    'Derived variable to indicate how many times a bridge, tunnel, the abutments, handrails were struck in the crash.',
    'Derived variable to indicate how many buses were involved in the crash (excluding school buses which are counted in the SCHOOL_BUS field).',
    'Derived variable to indicate how many cars or station wagons were involved in the crash.',
    "Derived variable to indicate how many times a 'cliff' or 'bank' was struck in the crash. This includes retaining walls",
    "The direction (dirn) of the crash from the reference point. Values possible are 'North', 'East', 'South' or 'West'.",
    "The distance (dist) of the crash from the reference point for the crash. The reference point is often the intersection of 'crash road' and 'side road' (refer to 'cr_rd_sd_rd' variable).",
    "The financial (fin) year in which a crash occurred, if known. This is displayed as a string field. eg 2004/2005",
    "Part 1 of the 'crash location' (crash_locn). May be a road name, route position (RP), landmark, or other, e.g. 'Ninety Mile Beach'. Used for location descriptions in reports etc.",
    "Part 2 of the 'crash location' (crash_locn). May be a side road name, landmark etc. Used for location descriptions in reports etc.",
    "The severity of a crash. Possible values are 'F' (fatal), 'S' (serious), 'M' (minor), 'N' (non-injury).",
    "A description (desc) of the state highway (SH) closest to the crash site, if applicable.",
    "The year (yr) in which a crash occurred. This is displayed as a number.",
    "Derived variable to indicate how many times debris was struck in the crash. Debris includes wood, boxes, paper, and other similar items that can fall off vehicles.",
    "The role of the road (refer to 'road_id') in the crash. Values possible are 'Main', 'Side', 'Both', 'Off', 'NotApplicable'.",
    "Derived variable to indicate how many times a ditch was struck in the crash.",
    "The 'easting' of the crash site.",
    "The number of fatalities resulting from the crash.",
    "Derived variable to indicate how many times a fence was struck in the crash.",
    "Derived variable to indicate how many times a flat, hill, rise, or crest was struck in the crash.",
    "Derived variable to indicate how many times a guard rail was struck in the crash.",
    "Derived variable to indicate how many times a holiday place (e.g. a holiday home, camping site, caravan site etc.) was struck in the crash.",
    "Derived variable to indicate how many times a house or building was struck in the crash.",
    "The location type of the crash. Possible values are 'Intersection', 'Midblock', 'Bridge', 'Off road', 'Unknown'.",
    "Derived variable to indicate how many times a kerb was struck in the crash.",
    "Derived variable to indicate how many times a traffic signal was struck in the crash.",
    "The unique identifier of a meshblock.",
    "The number of minor injuries resulting from the crash.",
    "Derived variable to indicate how many mopeds were involved in the crash.",
    "Derived variable to indicate how many motorcycles were involved in the crash.",
    "The 'northing' of the crash site.",
    "The number of lanes (number) available at the crash site.",
    "Derived variable to indicate how many times an object was thrown or dropped (excluding objects thrown or dropped by people) in the crash.",
    "Derived variable to indicate how many times other objects were struck in the crash. This includes all objects not covered in any other attribute.",
    "Derived variable to indicate how many times other vehicle types not covered in any other attribute were struck in the crash.",
    "Derived variable to indicate how many times the vehicle (veh) went over a bank in the crash.",
    "Derived variable to indicate how many times a parked vehicle (veh) was struck in the crash.",
    "Derived variable to indicate how many times a phone box or similar structure was struck in the crash.",
    "Derived variable to indicate how many pedestrians were involved in the crash.",
    "Derived variable to indicate how many times a post or pole was struck in the crash.",
    "The region (reg) in which the crash occurred. This is displayed as a string field.",
    "Derived variable to indicate how many times the road character was struck in the crash. This includes bridges, tunnels, culverts, intersections etc.",
    "The number of lanes (number) in which the crash occurred.",
    "Derived variable to indicate how many times road markings were struck in the crash.",
    "Derived variable to indicate how many times the road surface was struck in the crash.",
    "Derived variable to indicate how many times roadworks were struck in the crash.",
    "Derived variable to indicate how many school buses were involved in the crash.",
    "The number of serious injuries resulting from the crash.",
    "Derived variable to indicate how many times a slip or flood was struck in the crash.",
    "The speed limit in force at the crash site at the time of the crash.",
    "Derived variable to indicate how many times a stray animal was struck in the crash.",
    "Derived variable to indicate how many times a street light was struck in the crash.",
    "Derived variable to indicate how many SUVs were involved in the crash.",
    "Derived variable to indicate how many taxis were involved in the crash.",
    "The unique identifier of a territorial local authority (TLA).",
    "The name (name) of the territorial local authority (TLA) in which the crash occurred.",
    "Derived variable to indicate how many times a temporary speed limit was in force at the crash site.",
    "Derived variable to indicate how many times a traffic control device was struck in the crash.",
    "Derived variable to indicate how many times a traffic island was struck in the crash.",
    "Derived variable to indicate how many times a traffic sign was struck in the crash.",
    "Derived variable to indicate how many times a train was struck in the crash.",
    "Derived variable to indicate how many times a tree was struck in the crash.",
    "Derived variable to indicate how many trucks were involved in the crash.",
    "Derived variable to indicate how many times an unknown vehicle type was struck in the crash.",
    "Derived variable to indicate how many times an urban area was struck in the crash.",
    "Derived variable to indicate how many vans or utilities were involved in the crash.",
    "Derived variable to indicate how many vehicles were involved in the crash.",
    "Derived variable to indicate how many times a water or river was struck in the crash.",
    "Derived variable to indicate how many times weather conditions contributed to the crash.",
    "Derived variable to indicate how many times weather conditions contributed to the crash."
  )
)

# Print the R dataframe
crash_data_descriptions

