---
title: "Crash Data Exploratory Data Analysis"
output:
  html_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages(c('dplyr','ggplot2','skimr','ggcorrplot','tidyr', 'pander'))
library(ggcorrplot)
library(dplyr)
library(ggplot2)
library(skimr)
library(tidyr)
library(pander)
options(scipen = 999)

```

```{r}
#head(summary)
```


```{r}
crash_data = read.csv('../Data/crash_data.csv')

```



### Advisory Speed Distribution

```{r}
ggplot(crash_data, aes(x = speedLimit)) + 
  geom_histogram(binwidth = 5) +
  theme_minimal() +
  labs(x = "Advisory Speed", y = "Count", title = "Speed Limit Distribution")+ 
  scale_x_continuous(breaks = seq(0, 100, by = 10))

```

### Speed Limit Distribution

```{r}
ggplot(crash_data, aes(x = advisorySpeed)) + 
  geom_histogram(binwidth = 5) +
  theme_minimal() +
  labs(x = "Advisory Speed", y = "Count", title = "Advisory Speed Distribution") + 
  scale_x_continuous(breaks = seq(0, 100, by = 10))

```


### Boxplot of advisorySpeed vs crashSeverity

```{r}
ggplot(crash_data, aes(x = crashSeverity, y = advisorySpeed, fill = crashSeverity)) + 
  geom_boxplot(notch=TRUE) +
  ggtitle("Advisory Speed vs Crash Severity") +
  xlab("Crash Severity") + 
  ylab("Advisory Speed") + 
  scale_fill_manual(values = severity_colors)
```

####Number of lanes 
```{r}
ggplot(crash_data, aes(x = NumberOfLanes)) + 
  geom_bar() +
  ggtitle("Distribution of Number of Lanes") +
  xlab("Number of Lanes") + 
  ylab("Count")+ 
  scale_x_continuous(breaks = seq(0, 10, by = 1))

```
# Summing fatalities by different vehicle types

```{r}

# Summarize the data
fatalities_by_vehicle <- crash_data %>%
  summarise(
    Bicycle = sum(bicycle * fatalCount, na.rm = TRUE),
    Bus = sum(bus * fatalCount, na.rm = TRUE),
    Car_StationWagon = sum(carStationWagon * fatalCount, na.rm = TRUE),
    Moped = sum(moped * fatalCount, na.rm = TRUE),
    Motorcycle = sum(motorcycle * fatalCount, na.rm = TRUE),
    SUV = sum(suv * fatalCount, na.rm = TRUE),
    Taxi = sum(taxi * fatalCount, na.rm = TRUE),
    Truck = sum(truck * fatalCount, na.rm = TRUE),
    Unknown_Vehicle = sum(unknownVehicleType * fatalCount, na.rm = TRUE),
    Van_Utility = sum(vanOrUtility * fatalCount, na.rm = TRUE)
  )

# Convert to a longer format
longer <- fatalities_by_vehicle %>% 
  pivot_longer(
    everything(),
    names_to = 'Type',
    values_to = 'Fatalities'
  )


# Create the barplot
ggplot(longer, aes(x = reorder(Type, -Fatalities), y = Fatalities)) + 
  geom_bar(stat = 'identity') +
  ggtitle("Fatalities by Vehicle Type") +
  xlab("Vehicle Type") + 
  ylab("Fatalities")+ 
  theme(axis.text.x = element_text(angle = 90))
```



#### Fatalities by year 

```{r}
fatalities_by_year <- crash_data %>%
  group_by(crashYear) %>%
  summarise(Total_Fatalities = sum(fatalCount, na.rm = TRUE))

ggplot(fatalities_by_year,aes(x = crashYear, y = Total_Fatalities)) +
  geom_line() +
  geom_point() +
  theme_minimal() +
  labs(title = "Fatalities by Year", y = "Number of Fatalities")+ 
  scale_x_continuous(breaks = seq(2000, 2023, by = 2))+ 
  scale_y_continuous(breaks = seq(0, 500, by = 50))

```

#### Fatalities by weather A 

```{r}
fatalities_by_weather <- crash_data %>%
  group_by(weatherA) %>%
  summarise(Total_Fatalities = sum(fatalCount, na.rm = TRUE))

ggplot(fatalities_by_weather, aes(x = reorder(weatherA, -Total_Fatalities), y = Total_Fatalities)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Fatalities by Weather Condition (A)", y = "Number of Fatalities") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


#### Fatalities by weather B 
```{r}
fatalities_by_weatherB <- crash_data %>%
  group_by(weatherB) %>%
  summarise(Total_Fatalities = sum(fatalCount, na.rm = TRUE))%>%
  filter(weatherB != 'Null')

ggplot(fatalities_by_weatherB, aes(x = reorder(weatherB, -Total_Fatalities), y = Total_Fatalities)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Fatalities by Weather Condition (B)", y = "Number of Fatalities") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```






#### Crash Severity


```{r}
total_crashes_by_region <- crash_data %>%
  group_by(region) %>%
  summarise(total_crashes = n())

# Step 2: Calculate the proportion of each type of crash within each region
crash_severity_by_region <- crash_data %>%
  group_by(crashSeverity, region) %>%
  summarise(n = n()) %>%
  left_join(total_crashes_by_region, by = "region") %>%
  mutate(proportion = n / total_crashes)

crash_severity_by_region <- crash_severity_by_region %>% 
    filter(!is.na(region) & region != "")

crash_severity_by_region$crashSeverity <- factor(crash_severity_by_region$crashSeverity, 
      levels = c("Non-Injury Crash", "Minor Crash", "Serious Crash", "Fatal Crash"))

crash_data$crashSeverity <- factor(crash_data$crashSeverity,  levels = c("Non-Injury Crash", "Minor Crash", "Serious Crash", "Fatal Crash"))

severity_colors <- c("Non-Injury Crash" = "#8DB3AD", "Minor Crash" = "#F5D7B1", "Serious Crash" = "#F05161", "Fatal Crash" = '#262626')
```

```{r}

ggplot(crash_data, aes(x = crashSeverity, fill = crashSeverity)) +
  geom_bar() +
  theme_minimal() +
  labs(x = "Crash Severity", y = "Count", title = "Crash Severity Counts") + 
  scale_fill_manual(values = severity_colors)


# Create the first plot
ggplot(crash_severity_by_region, aes(x = region, y = proportion, fill = crashSeverity)) +
  geom_bar(stat = 'identity') +
  facet_wrap(~crashSeverity, scales = "free_y") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0)) +
  labs(title = 'Proportion of Crash Severity by Region',
       x = 'Region',
       y = 'Proportion of Crashes') +
  scale_fill_manual(values = severity_colors)  # Apply custom colors

# Create the second plot
ggplot(crash_severity_by_region, aes(x = region, y = proportion, fill = crashSeverity)) +
  geom_bar(stat = 'identity') +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(
    title = "Proportion of Crash Severity by Region",
    x = "Region",
    y = "Proportion"
  ) +
  scale_fill_manual(values = severity_colors) 



```


```{r}

fatal_summary <- crash_data %>%
  filter(crashSeverity == "Fatal Crash") %>%
  group_by(crashYear, region) %>%
  summarise(total_fatal = sum(fatalCount)) %>%
  ungroup()

ggplot(fatal_summary, aes(x=crashYear, y=region)) +
  geom_tile(aes(fill=total_fatal)) +
  scale_fill_gradient(low="white", high="red") +
  ggtitle("Heatmap of Total Fatal Crashes by Year and Region") +
  xlab("Year") +
  ylab("Region")


```
=



